name: Release CLI Tool
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build and Publish CLI Tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: mvn clean package -Pcli
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/rpm-adapter.jar
          asset_name: rpm-adapter.jar
          tag: ${{ github.ref }}
          overwrite: true